function create_boxcar(subj,dir_input)

    %  Create a new figure for boxcar customization
    
    cb.f = figure('Name', 'Create customized boxcar',...
                    'Visible','on',...
                    'Position',[400,800,500,300]);
    
    %  Create data entry boxes for customized boxcar - user enters start and
    %  end times 

    cb.number_blocks = uicontrol('Style','edit',...
                                'Units','pixels',...
                                'Enable','on',...
                                'Position',[200,260,100,20]);
                            
    cb.start_delay = uicontrol('Style','edit',...
                        'Units','pixels',...
                        'Enable','on',...
                        'Position',[200,210,100,20]);                      

    cb.break_duration = uicontrol('Style','edit',...
                                'Units','pixels',...
                                'Enable','on',...
                                'Position',[200,160,100,20]);   

    cb.break_after_block = uicontrol('Style','edit',...
                                'Units','pixels',...
                                'Enable','on',...
                                'Position',[200,110,100,20]);         

    cb.breathhold_duration = uicontrol('Style','edit',...
                                    'Units','pixels',...
                                    'Enable','on',...
                                    'Position',[200,60,100,20]);

    cb.normal_breathing_duration = uicontrol('Style','edit',...
                                            'Units','pixels',...
                                            'Enable','on',...
                                            'Position',[200,10,100,20]);                                    

    %  Descriptive text for customized boxcar data entry fields

    cb.number_blocks_text = uicontrol('Style','text',...
                    'units','normalized',...
                    'Position',[0.05,0.88,0.3,0.05],...
                    'String','Number of blocks:');

    cb.start_delay_text = uicontrol('Style','text',...
                    'units','normalized',...
                    'Position',[0.05,0.71,0.3,0.05],...
                    'String','Start Delay:');            
                
    cb.break_duration_text = uicontrol('Style','text',...
                    'units','normalized',...
                    'Position',[0.05,0.54,0.3,0.05],...
                    'String','Break duration:');
                
    cb.break_after_block_text = uicontrol('Style','text',...
                                    'units','normalized',...
                                    'position',[0.05,0.37,0.3,0.05],...
                                    'String','Break after block:');

    cb.breathhold_duration_text = uicontrol('Style','text',...
                                        'units','normalized',...
                                        'Position',[0.05,0.20,0.3,0.05],...
                                        'String','Breathhold duration:');

    cb.normal_breathing_duration_text = uicontrol('Style','text',...
                                                'units','normalized',...
                                                'Position',[0,0.04,0.4,0.05],...
                                                'String','Normal breathing duration:');

    %  Create push button to create customized boxcar
    cb.createboxcar = uicontrol('Style','togglebutton',...
                              'Visible','on',...
                              'String','Create Boxcar',...
                              'Enable','off',...
                              'Value',0,'Position',[350,150,150,45],...
                              'Callback',{@create_boxcar_textfile,subj,dir_input});

    %  Create push button to use customized boxcar (user can re-enter data in
    %  fields until this button is pressed) 
    cb.viewboxcar = uicontrol('Style','togglebutton',...
                              'Visible','on',...
                              'String','View Boxcar',...
                              'Enable','off',...
                              'Value',0,'Position',[350,90,150,45],...
                              'Callback',{@viewboxcar,subj,dir_input});
    guidata(cb.f,cb);   
    
    waitfor(cb.normal_breathing_duration,'String');
    set(cb.createboxcar,'Enable','on');
    