function create_HVboxcar(source,callbackdata,subj,dir_input,sp)

handles = guidata(source);

same_boxcar = 0;

breath = 3;

if handles.custom(3).Value == 1
    %  Create a new figure for boxcar customization
    
    cbHV.f = figure('Name', 'Create customized HV boxcar',...
                    'Visible','on',...
                    'Position',[1450,800,500,300],...
                    'numbertitle','off');
    
    %  Create data entry boxes for customized boxcar - user enters start and
    %  end times 

    cbHV.number_blocks = uicontrol('Style','edit',...
                                'Units','pixels',...
                                'Enable','on',...
                                'Position',[200,260,100,20]);
                            
    cbHV.start_delay = uicontrol('Style','edit',...
                        'Units','pixels',...
                        'Enable','on',...
                        'Position',[200,210,100,20]);                      

    cbHV.break_duration = uicontrol('Style','edit',...
                                'Units','pixels',...
                                'Enable','on',...
                                'Position',[200,160,100,20]);   

    cbHV.break_after_block = uicontrol('Style','edit',...
                                'Units','pixels',...
                                'Enable','on',...
                                'Position',[200,110,100,20]);         

    cbHV.breathhold_duration = uicontrol('Style','edit',...
                                    'Units','pixels',...
                                    'Enable','on',...
                                    'Position',[200,60,100,20]);

    cbHV.normal_breathing_duration = uicontrol('Style','edit',...
                                            'Units','pixels',...
                                            'Enable','on',...
                                            'Position',[200,10,100,20]);                                    

    %  Descriptive text for customized boxcar data entry fields

    cbHV.number_blocks_text = uicontrol('Style','text',...
                    'units','normalized',...
                    'Position',[0.05,0.88,0.3,0.05],...
                    'String','Number of blocks:');

    cbHV.start_delay_text = uicontrol('Style','text',...
                    'units','normalized',...
                    'Position',[0.05,0.71,0.3,0.05],...
                    'String','Start Delay:');            
                
    cbHV.break_duration_text = uicontrol('Style','text',...
                    'units','normalized',...
                    'Position',[0.05,0.54,0.3,0.05],...
                    'String','Break duration:');
                
    cbHV.break_after_block_text = uicontrol('Style','text',...
                                    'units','normalized',...
                                    'position',[0.05,0.37,0.3,0.05],...
                                    'String','Break after block:');

    cbHV.breathhold_duration_text = uicontrol('Style','text',...
                                        'units','normalized',...
                                        'Position',[0.05,0.20,0.3,0.05],...
                                        'String','Breathhold duration:');

    cbHV.normal_breathing_duration_text = uicontrol('Style','text',...
                                                'units','normalized',...
                                                'Position',[0,0.04,0.4,0.05],...
                                                'String','Normal breathing duration:');

    %  Create push button to create customized boxcar
    cbHV.createboxcar = uicontrol('Style','togglebutton',...
                              'Visible','on',...
                              'String','Create Boxcar',...
                              'Enable','off',...
                              'Value',0,'Position',[350,150,150,45],...
                              'Callback',{@create_boxcar_textfile,subj,dir_input,breath,sp,same_boxcar});

    %  Create push button to use customized boxcar (user can re-enter data in
    %  fields until this button is pressed) 
    cbHV.viewboxcar = uicontrol('Style','togglebutton',...
                              'Visible','on',...
                              'String','View Boxcar',...
                              'Enable','off',...
                              'Value',0,'Position',[350,90,150,45],...
                              'Callback',{@viewboxcar,subj,dir_input,breath});
    guidata(cbHV.f,cbHV);   
    
    waitfor(cbHV.normal_breathing_duration,'String');
    set(cbHV.createboxcar,'Enable','on');        
    set(sp.start,'Enable','on');
else
    figures_to_close = findall(0,'Type','figure'); %  Close the BH customize boxcar figure
    display(figures_to_close);
    close('Create customized HV boxcar');
end
end
                          