function create_boxcar(subj,directories,main_GUI,timeseries,completely,funct)
% Function to get breathhold data from user to create a customized boxcar for BH1 and BH2 - assuming that
% the same boxcar should be used for both 
% 
% INPUTS 
%     subj - subject data (name, breathhold, date)
%     directories - all directory path info 
%     main_GUI - data from the main interface
%     timeseries - filepath for the .1D timeseries file 
%     completely - 1:indicates if the user selected the completely customized
%     boxcar method 
%     funct - functional data 
% 
% *************** REVISION INFO ***************
% Original Creation Date - June 22, 2016
% Author - Hannah Sennik

%  Create a new figure for boxcar customization
cb.f = figure('Name', ['Create customized boxcar for: ' subj.breathhold],...
                'Visible','on',...
                'Position',[358,156,600,370],...
                'numbertitle','off');
set(cb.f, 'MenuBar', 'none'); % remove the menu bar 
set(cb.f, 'ToolBar', 'none'); % remove the tool bar  


%  Create data entry boxes for customized boxcar 
cb.user_instructions = uicontrol('Style','text',...
                                'units','normalized',...
                                'Position',[0.15,0.94,0.7,0.05],...
                                'String','Please enter all values in seconds, NOT number of TRs.');
                            
if completely == 0 
    cb.user_instructions2 = uicontrol('Style','text',...
                                    'units','normalized',...
                                    'Position',[0,0.89,1,0.05],...
                                    'String','This tool assumes all blocks are of equal length. Press more options if this is not the case.');        
end

%  Create edit box for number of blocks in boxcar 
cb.number_blocks = uicontrol('Style','edit',...
                            'Units','pixels',...
                            'Enable','on',...
                            'Position',[235,300,100,20]);
                        
if completely == 0
    start_delay_box_pos = [235,250,100,20];
    start_delay_text_pos = [0.05,0.67,0.3,0.05];
else
    start_delay_box_pos = [235,275,100,20];
    start_delay_text_pos = [0.05,0.74,0.3,0.05];
end

%  Create edit box for start delay                         
cb.start_delay = uicontrol('Style','edit',...
                            'Units','pixels',...
                            'Enable','on',...
                            'Position',start_delay_box_pos);   
                        
%  Descriptive text for customized boxcar data entry fields

cb.number_blocks_text = uicontrol('Style','text',...
                                'units','normalized',...
                                'Position',[0.05,0.81,0.3,0.05],...
                                'String','Number of blocks:');

cb.start_delay_text = uicontrol('Style','text',...
                                'units','normalized',...
                                'Position',start_delay_text_pos,...
                                'String','Start Delay:');                        

if completely == 0                        
    %  Create edit box for duration of break (if any) during study                         
    cb.break_duration = uicontrol('Style','edit',...
                                    'Units','pixels',...
                                    'Enable','on',...
                                    'Position',[235,200,100,20]);   

    %  Create edit box to specify which block the break comes after                         
    cb.break_after_block = uicontrol('Style','edit',...
                                    'Units','pixels',...
                                    'Enable','on',...
                                    'Position',[235,150,100,20]);         

    %  Create edit box to specify the duration of each breathhold (assuming all
    %  are the same)
    cb.breathhold_duration = uicontrol('Style','edit',...
                                    'Units','pixels',...
                                    'Enable','on',...
                                    'Position',[235,100,100,20]);

    %  Create edit box to specify the duration of normal breathing periods
    %  (assuming all are the same)
    cb.normal_breathing_duration = uicontrol('Style','edit',...
                                            'Units','pixels',...
                                            'Enable','on',...
                                            'Position',[235,50,100,20]);  

    cb.break_duration_text = uicontrol('Style','text',...
                                    'units','normalized',...
                                    'Position',[0.05,0.53,0.3,0.05],...
                                    'String','Break duration:');

    cb.break_after_block_text = uicontrol('Style','text',...
                                        'units','normalized',...
                                        'position',[0.05,0.40,0.3,0.05],...
                                        'String','Break after block:');

    cb.breathhold_duration_text = uicontrol('Style','text',...
                                        'units','normalized',...
                                        'Position',[0.05,0.27,0.3,0.05],...
                                        'String','Breathhold duration:');

    cb.normal_breathing_duration_text = uicontrol('Style','text',...
                                                'units','normalized',...
                                                'Position',[0,0.13,0.37,0.05],...
                                                'String','Normal breathing duration:');

    %  Create push button to completely customize the boxcar
    cb.completelycustomized = uicontrol('Style','pushbutton',...  
                                        'Visible','on',...
                                        'String','More options',...
                                        'Enable','on',...
                                        'Value',0,'Position',[400,210,150,45],...
                                        'Callback',{@completelycustomized,subj,directories,main_GUI,timeseries,funct}); % brings up another interface that allows for complete boxcar customization                                    
else
    
    cb.block_number_text = uicontrol('Style','text',...
                                'Units','normalized',...
                                'Position',[0.05,0.53,0.2,0.1],...
                                'String','Block Number');
                        
    cb.breathhold_duration_text = uicontrol('Style','text',...
                                            'Units','normalized',...
                                            'Position',[0.25,0.53,0.2,0.1],...
                                            'String','Breathhold Duration');
  
    cb.breathhold_duration_text = uicontrol('Style','text',...
                                            'Units','normalized',...
                                            'Position',[0.45,0.53,0.2,0.1],...
                                            'String','Normal Breathing Duration');
                                        
    waitfor(cb.number_blocks,'String');
    
    for i = 1:str2double(cb.number_blocks.String)
        cb.block_number(i) = uicontrol('Style','text',...
                                    'Units','normalized',...
                                    'Position',[0.05,0.41 - ((i/100)*6),0.2,0.1],...
                                    'String',i);
                                
        cb.breathhold(i) = uicontrol('Style','edit',...
                                'Units','pixels',...
                                'Enable','on',...
                                'Position',[160,175 - (i*22),100,20]); 
                            
        cb.normal(i) = uicontrol('Style','edit',...
                                 'Units','pixels',...
                                 'Enable','on',...
                                 'Position',[280,175 - (i*22),100,20]);
    end
    %  Create refresh button.
    cb.again = uicontrol('Style','pushbutton',...
                        'Visible','on',...
                        'Enable','on',...
                        'Value',0,'Position',[565,335,30,30],...
                        'callback',@refresh_customized);  

    icon=imread([directories.matlabdir '/refresh.png']);
    set(cb.again,'CData',icon);
    
end 

if completely == 0
    position1 = [400,150,150,45];
    position2 = [400,90,150,45];
else
    position1 = [450,150,150,45];
    position2 = [450,90,150,45];
end

%  Create push button to create customized boxcar from entered data 
cb.createboxcar = uicontrol('Style','pushbutton',...
                          'Visible','on',...
                          'String','Create Boxcar',...
                          'Enable','on',...
                          'Value',0,'Position',position1,...
                          'Callback',{@create_boxcar_textfile,subj,directories,main_GUI,completely}); % saves the data from the gui to a .1D file to be used as a boxcar 

%  Create push button to view customized boxcar (user can re-enter data in
%  fields until this button is pressed) 
cb.viewboxcar = uicontrol('Style','pushbutton',...
                          'Visible','on',...
                          'String','View Boxcar',...
                          'Enable','off',...
                          'Value',0,'Position',position2,...
                          'Callback',{@viewboxcar,subj,directories,timeseries,main_GUI,funct}); % calls plotfiles to view the customized boxcar that was created 


%  Get figure data 
guidata(cb.f,cb);   

end