% GUI for clinician to fully process and analyze a subject who has
% undergone a CVR study 
% 
% File Name: generate_report.m
% 
% NOTES - HS - 16/08/05 - Initial Creation
% 
% AUTHOR - Hannah Sennik
% Created - 2016-08-05

clear all; % Clear all variables
close all; % Close all windows 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% INITIALIZING VARIABLES

addpath('/data/wayne/matlab/NIFTI'); % path to nii functions
directories.main = ('/data/projects/CVR/GUI_subjects'); % base directory where all CVR subjects are stored
cd(directories.main); % change to this directory
subject_names = dir(directories.main); % get subject names from main directory 
subj = ''; % initialize subj variable (struct)
subj.date = '160314'; % What is this - is it the same for all subjects?
directories.subject = ''; % initialize subject directory
directories.matlabdir = '/data/hannahsennik/MATLAB/CVR_GUI'; % specify the matlab directory that contains python and standard files 
directories.REDCapdir = 'REDCap_import_files'; % directory name for REDCap files 
directories.metadata = 'metadata'; % directory name for subject specific files to be inputted to pipeline
directories.textfilesdir = 'textfiles'; % directory name for output of textfiles generated by this program 
directories.timeseries = 'timeseries'; % directory name for output of .1D files generated by this program 
directories.flirtdir = 'flirt';

%  SUBJECT DATA
fileID = fopen([directories.matlabdir '/subject_name.txt'],'r'); % Subject name is pulled from this textfile (this is the subject that was just fully processed and analyzed)
subj.name = fscanf(fileID,'%s\n');
fclose(fileID);

%  Create the entire interface panel
sp.f = figure('Name', ['Clinical Report: ' subj.name],...
                        'Visible','on',...
                        'Position',[50,800,800,900],...
                        'numbertitle','off');
set(sp.f, 'MenuBar', 'none'); % remove the menu bar 
set(sp.f, 'ToolBar', 'none'); % remove the tool bar 