%  PROCESS SUBJECT ENTIRELY 

%  Step 1: Clinician specifies location of raw subject data via a select
%  folder popup. Should be able to get subject name, date associated with data, and breath hold method. 

%  Simple UI that displays subject selection and GO button to PROCESS
%  SUBJECT. Generates files that are used for display later. User can then
%  LOOK AT SUBJECT by choosing to run the display GUI.

addpath('/data/wayne/matlab/NIFTI'); % path to nii functions
directory = ('/data/projects/CVR/GUI_subjects/'); % base directory where all CVR subjects are stored
cd(directory); % change to this directory 
subject_names = dir(directory);

%  Create the entire interface panel 
sp.f = figure('Name', 'Process and Analyze Subject',...
                    'Visible','on',...
                    'Position',[50,800,300,500]);
    
%  Descriptive text for the select subject dropdown menu                
sp.text(1) = uicontrol('Style','text',...
                'units','normalized',...
                'Position',[0.35,0.73,0.3,0.2],...
                'String','Select subject');
        
%  Create the popupmenu to select subject to process

sp.STR = {subject_names.name}; % pull the directory names of patients from directory where CVR subjects are stored 
sp.menu(1) = uicontrol('Style','popupmenu',...
                'Visible','on',...
                'String',sp.STR,...
                'Position',[50,400,200,25]);

waitfor(sp.menu(1),'Value');   % Wait for a subject to be selected            
set(sp.menu(1),'Enable','off'); % Disable subject field 
temp_name = sp.menu(1).String(sp.menu(1).Value); 
subj.name = temp_name{1}; 
display(subj.name);

dir_input = strcat(directory,subj.name,'/');
cd(dir_input); % Change to subject's directory 
subj.date = '160314'; % What is this 

fileID = fopen('/data/hannahsennik/MATLAB/CVR_GUI/subject_name.txt','w+'); % Open the subject name text file in write mode
         format = '%s\n';
         fprintf(fileID,format,subj.name); % Write the subject name to file - this is used in the main GUI to look at subject data 
         fclose(fileID);
display('Subject name file created');

%  Create radiobuttons to select between standard and customized boxcar (can
%  only choose one or the other) 

%  Radiobutton for standard single staggered boxcar 
sp.boxcar(1) = uicontrol('Style','radiobutton',...
                        'Visible','on',...
                        'Units','pixels',...
                        'String','Standard Single Staggered',...
                        'HandleVisibility','on',...
                        'Position',[50,350,200,25],...
                        'Enable','on',...
                        'Callback',{@myRadio,subj,dir_input});

%  Radiobutton for customized boxcar 
sp.boxcar(2) = uicontrol('Style','radiobutton',...
                        'Visible','on',...
                        'Units','pixels',...
                        'String','Customized Boxcar',...
                        'HandleVisibility','on',...
                        'Position',[50,300,200,25],...
                        'Enable','on',...
                        'Callback',{@myRadio,subj,dir_input});

%  Get figure data for myRadio callback so that only one radiobutton can be
%  selected at a time 
guidata(sp.f,sp);                        

%  Create push button to begin processing subject.
sp.start = uicontrol('Style','togglebutton',...
                'Visible','on',...
                'String','Process and Analyze Subject',...,
                'Enable','on',...
                'Value',0,'Position',[50,110,200,60],...
                'callback',{@startprocessing,subj,dir_input});

%  Create push button to look at subject data after processing and analysis
%  is complete 
sp.look = uicontrol('Style','pushbutton',...
                   'Visible','on',...
                   'String','Look at Subject Data',...
                   'Value',0,'Position',[50,30,200,60],...
                   'Enable','off',...
                   'callback',@run_again);           




