% This is the main interface that clinicians will come to when starting the
% process of analyzing a CVR patient 
% 
% There are three main options
% 1. Process and Analyze the Subject
% 2. View the Subject Data
% 3. Generate Clinical Report 
%
% The idea is that the clinican can go back and forth between 1 and 2 until
% the subject has been entirely processed and analyzed. Step 3 occurs once
% 1 and 2 are completely done and the clinician is ready to make a report
% based on the data generated.
% 
% File Name: SickKids_CVR.m
% 
% NOTES - HS - 16/08/02 - Initial Creation
% 
% AUTHOR - Hannah Sennik
% Created - 2016-08-02

clear all; % clear all variables
close all; % close all figures 

%  Create the entire interface panel
main.f = figure('Name', 'SickKids CVR',...       
                        'Visible','on',...l
                        'Position',[50,800,300,300],...
                        'numbertitle','off');
set(main.f, 'MenuBar', 'none'); % remove the menu bar 
set(main.f, 'ToolBar', 'none'); % remove the tool bar    

%  Create push button to process and analyze the subject
main.process_analyze = uicontrol('Style','pushbutton',...
                             'Visible','on',...
                             'String','Step 1: Process/Analyze',...
                             'Enable','on',...
                             'Value',0,'Position',[50,210,200,60],...
                             'callback',@first_gui_again); % This function runs process_subject.m 

%  Create push button to view the subject data after processing and analysis                         
main.view_data = uicontrol('Style','pushbutton',...
                             'Visible','on',...
                             'String','Step 2: View Data',...
                             'Enable','on',...
                             'Value',0,'Position',[50,130,200,60],... 
                             'callback',@run_again); % This function runs look_at_CVR_data.m

%  Create push button to generate a clinical report                          
main.generate_report = uicontrol('Style','pushbutton',...
                             'Visible','on',...
                             'String','Step 3: Clinical Report',...
                             'Enable','on',...
                             'Value',0,'Position',[50,50,200,60],...
                             'callback',@run_report); % This function runs generate_report.m                         
