clear all;
close all;

global ax_slider_value; %make handles instead
global cor_slider_value;
global sag_slider_value;
global button_state;
ax_slider_value = 0;
cor_slider_value = 0;
sag_slider_value = 0;
button_state = 0;

addpath('/data/wayne/matlab/NIFTI');
dir_input = '/data/projects/CVR/metadata/sandbox/test_files';

fname_anat = 'T1_nii.nii';
fname_cereb = 'T1_cerebellar.nii';
% fname_anat = 'ChanR16_anat_brain.nii';
% fname_cereb = 'cereb_Chan_stand2target.nii';
% fname_map = 'ChanR16_BH1_CVR_160314_glm_buck.nii';

anatomical_view = load_nii([dir_input '/' fname_anat]);
% Change to number of voxels?   
% Voxel size (kind of dimension)
cereb_overlay = load_nii([dir_input '/' fname_cereb]);
% CVRmap = load_nii([dir_input '/' fname_map]);

% Constructing the anatomical slices

[voxx voxy voxz] = size(anatomical_view.img);

slice_x = 1; %30 
slice_y = 1; %75
slice_z = 1; %70

xrange = [1:voxx];
yrange = [1:voxy];
zrange = [1:voxz]; %change back to 190 for original sandbox images

numx = length(xrange);
numy = length(yrange);
numz = length(zrange);

sigmin = 10; %10
sigmax = 500; %500
    
slice_ax = (double(repmat(imresize(squeeze(anatomical_view.img(:,:,slice_z)),[voxx voxy]), [1 1 3]))- sigmin) / sigmax ;
slice_cor = (double(repmat(imresize(squeeze(anatomical_view.img(:,slice_y,:)),[voxx voxz]), [1 1 3])) - sigmin) / sigmax;
slice_sag = (double(repmat(imresize(squeeze(anatomical_view.img(slice_x,:,:)),[voxy voxz]), [1 1 3])) - sigmin) / sigmax;

slice_ax = rot90(slice_ax(xrange,yrange,:));
slice_cor = rot90(slice_cor(xrange,zrange,:));
slice_sag = rot90(slice_sag(yrange,zrange,:));

%  Create main panel window with controls
main_panel = figure('Name', 'CVR Menu',...
                    'Visible','on',...
                    'Position',[50,800,300,100]);
                
% Toggle button to overlay pf mask
tb = uicontrol('Style','togglebutton',...
                'Visible','on',...
                'String','Overlay posterior fossa mask',...
                'Value',0,'Position',[50,20,200,60],...
                'callback',@pushstate);
            
%  Toggle button to overlay CVR map
tb2 = uicontrol('Style','togglebutton',...
                'Visible','on',...
                'String','Overlay CVR map',...
                'Value',0,'Position',[50,100,200,60],...
                'callback',@pushstate);
            
%Dropdown menu to switch between mapping methods
htext  = uicontrol('Style','text','String','CVR Mapping Method',...
           'Position',[536,50,150,15]);
hpopup = uicontrol('Style','popupmenu',...
           'String',{'Posterior Fossa','Stimulate File','Resp. Data', 'Resp. Bellows', 'End Tidal CO2'},...
           'Position',[550,20,125,25],...
           'callback','');

%  Create window to display axial slices
f = figure('Name', 'Axial',...
            'Visible','on',...
            'Position',[50,200,600,500]);
   
%  Slider object to control axial slice position
ax_slider = uicontrol('style', 'slider',...
            'Min',1,'Max',voxz,'Value',1,... 
            'units', 'normalized',...
            'position',[0.04 0.45 0.08 0.25],...
            'callback',{@sliderpos_ax,slice_z,voxx,voxy,sigmin,sigmax,anatomical_view,xrange,yrange,cereb_overlay});
        
ax_text_slider = uicontrol('Style', 'text',....
            'units', 'normalized',...
            'position', [0.03 0.73 0.1 0.15],...
            'String', 'Axial Slice Position');
       
% %  Toggle button to overlay pf mask
% tb_pf_ax = uicontrol('Style','togglebutton',...
%                 'Visible','off',...
%                 'String','Overlay pf mask',...
%                 'Value',0,'Position',[20,20,150,40],...
%                 'callback',{@overlay_ax,slice_z,voxx,voxy,sigmin,sigmax,anatomical_view,xrange,yrange,cereb_overlay});

% %  Toggle button to overlay CVR map
% tb_CVR_ax = uicontrol('Style','togglebutton',...
%                 'Visible','off',...
%                 'String','Overlay CVR mask',...
%                 'Value',0,'Position',[20,20,150,40],...
%                 'callback',{@overlay_ax,slice_z,voxx,voxy,sigmin,sigmax,anatomical_view,xrange,yrange,CVRmap});

imshow(slice_ax);

%  Create window to display coronal slices
f2 = figure('Name', 'Coronal',...
            'Visible','on',...
            'Position',[675,200,600,500]);
              
%  Slider object to control coronal slice position
cor_slider = uicontrol('style', 'slider',...
            'Min',1,'Max',voxy,'Value',1,... 
            'units', 'normalized',...
            'position',[0.04 0.45 0.08 0.25],...
            'callback',{@sliderpos_cor,slice_y,voxx,voxz,sigmin,sigmax,anatomical_view,xrange,zrange,cereb_overlay});
        
cor_text_slider = uicontrol('Style', 'text',....
            'units', 'normalized',...
            'position', [0.03 0.73 0.1 0.15],...
            'String', 'Coronal Slice Position');

% %  Toggle button to overlay pf mask
% tb_pf_cor = uicontrol('Style','togglebutton',...
%                 'Visible','off',...
%                 'String','Overlay pf mask',...
%                 'Value',0,'Position',[20,20,150,40],...
%                 'callback',{@overlay_cor,slice_y,voxx,voxz,sigmin,sigmax,anatomical_view,xrange,zrange,cereb_overlay});
% 
% %  Toggle button to overlay CVR map
% tb_CVR_cor = uicontrol('Style','togglebutton',...
%                 'Visible','off',...
%                 'String','Overlay CVR map',...
%                 'Value',0,'Position',[20,20,150,40],...
%                 'callback',{@overlay_cor,slice_y,voxx,voxz,sigmin,sigmax,anatomical_view,xrange,zrange,CVRmap});

imshow(slice_cor);

%  Create window to display saggital slices
f3 = figure('Name', 'Saggital',...
            'Visible','on',...
            'Position',[1300,200,600,500]);
              
%  Slider object to control saggital slice position
sag_slider = uicontrol('style', 'slider',...
            'Min',1,'Max',voxx,'Value',1,... %value property changes as we move the slider
            'units', 'normalized',...
            'position',[0.04 0.45 0.08 0.25],...
            'callback',{@sliderpos_sag,slice_x,voxy,voxz,sigmin,sigmax,anatomical_view,yrange,zrange,cereb_overlay});
        
sag_text_slider = uicontrol('Style', 'text',....
            'units', 'normalized',...
            'position', [0.03 0.73 0.1 0.15],...
            'String', 'Saggital Slice Position');
       
% %  Toggle button to overlay pf mask
% tb_pf_sag = uicontrol('Style','togglebutton',...
%                 'Visible','off',...
%                 'String','Overlay pf mask',...
%                 'Value',0,'Position',[20,20,150,40],...
%                 'callback',{@overlay_sag,slice_x,voxy,voxz,sigmin,sigmax,anatomical_view,yrange,zrange,cereb_overlay});

% %  Toggle button to overlay CVR map
% tb_CVR_sag = uicontrol('Style','togglebutton',...
%                 'Visible','off',...
%                 'String','Overlay pf mask',...
%                 'Value',0,'Position',[20,20,150,40],...
%                 'callback',{@overlay_sag,slice_x,voxy,voxz,sigmin,sigmax,anatomical_view,yrange,zrange,CVRmap});
% 
imshow(slice_sag);


       

